"""Added price table

Revision ID: 3b0906e9a392
Revises: 
Create Date: 2025-12-02 15:38:02.062754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0906e9a392'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptoprice',
    sa.Column('id', sa.Integer(), nullable=False, comment='id.'),
    sa.Column('target', sa.Numeric(), nullable=False, comment='Таргет цены криптоактива.'),
    sa.Column('ticker', sa.String(), nullable=False, comment='Тикер.'),
    sa.Column('standard_name', sa.String(), nullable=False, comment='Стандартное название для апи получения.'),
    sa.Column('movement_direction', sa.Enum('DOWN', 'UP', name='cryptopricemovementdirection'), nullable=False, comment='Направление движения цены.'),
    sa.Column('last_saved', sa.Numeric(), nullable=False, comment='Последняя сохраненная цена.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='Признак активности таргета.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Время создания.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Время обновления.'),
    sa.CheckConstraint('last_saved > 0', name='last_saved_gt_0_check'),
    sa.CheckConstraint('target > 0', name='target_gt_0_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('name_target_uq', 'cryptoprice', ['ticker', 'target'], unique=True, sqlite_where=sa.text('is_active = True'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_target_uq', table_name='cryptoprice', sqlite_where=sa.text('is_active = True'))
    op.drop_table('cryptoprice')
    # ### end Alembic commands ###
