"""Add price_diff column

Revision ID: 9598832a52bf
Revises: dc72b926645b
Create Date: 2026-02-01 13:01:25.048265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9598832a52bf'
down_revision: Union[str, Sequence[str], None] = 'dc72b926645b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptoprice', sa.Column('price_diff', sa.Numeric(), sa.Computed('ROUND(ABS(last_saved - target) / ((target + last_saved) / 2.0) * 100, 5)', ), nullable=True, comment='Симметричный процент таргета и текущей цены'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptoprice', 'price_diff')
    # ### end Alembic commands ###
